# 01_csv.py

In [1]:
import pandas as pd

In [4]:
#devo alterar a referência quando ir ao VScode
df = pd.read_csv("/content/drive/MyDrive/PROJETOS/ESTUDO_IA_E_CIENCIA_DE_DADOS/Teo_me_Why/Pandas_2025/data/raw/clientes.csv", sep = ";")

In [5]:
df

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,001ebba5-5491-400a-ad05-d9204ea11cca,0,1,0,0,0,0,2026-07-16 23:10:15.533,2026-07-16 23:10:15.533
...,...,...,...,...,...,...,...,...,...
5824,ff66470f-614d-4a3e-ab57-831dcef5dec4,0,1,0,0,0,0,2026-08-05 21:41:21.980,2026-08-05 21:41:21.980
5825,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959
5826,ffcf3b9c-8cc8-4fca-a93a-e01a6fd830f0,1,1,1,0,0,0,2026-05-06 14:42:42.170,2026-05-06 14:44:23.800
5827,fff7862d-4b2c-4140-a4c5-509b48ed31b4,0,1,0,0,0,1000,2025-11-12 01:01:58.698,2025-11-12 01:02:16.561
5828,fff940d1-0786-4ee5-a75a-3bbda4e50f7a,0,1,0,0,0,0,2026-04-29 13:33:15.703,2026-04-29 13:33:15.703

In [7]:
df.to_csv("clientes.csv", index=False) # df.to_[tipo_de_arquivo] Salva a tabela no formato desejado

In [8]:
df.to_parquet("cliente.parquet", index=False)

In [11]:
df_2 = pd.read_parquet("/content/cliente.parquet")

In [12]:
df_2

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,001ebba5-5491-400a-ad05-d9204ea11cca,0,1,0,0,0,0,2026-07-16 23:10:15.533,2026-07-16 23:10:15.533
...,...,...,...,...,...,...,...,...,...
5824,ff66470f-614d-4a3e-ab57-831dcef5dec4,0,1,0,0,0,0,2026-08-05 21:41:21.980,2026-08-05 21:41:21.980
5825,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959
5826,ffcf3b9c-8cc8-4fca-a93a-e01a6fd830f0,1,1,1,0,0,0,2026-05-06 14:42:42.170,2026-05-06 14:44:23.800
5827,fff7862d-4b2c-4140-a4c5-509b48ed31b4,0,1,0,0,0,1000,2025-11-12 01:01:58.698,2025-11-12 01:02:16.561
5828,fff940d1-0786-4ee5-a75a-3bbda4e50f7a,0,1,0,0,0,0,2026-04-29 13:33:15.703,2026-04-29 13:33:15.703

In [13]:
df.to_excel("clientes.xlsx", index=False)

In [14]:
pd.read_excel("/content/clientes.xlsx")

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,001ebba5-5491-400a-ad05-d9204ea11cca,0,1,0,0,0,0,2026-07-16 23:10:15.533,2026-07-16 23:10:15.533
...,...,...,...,...,...,...,...,...,...
5824,ff66470f-614d-4a3e-ab57-831dcef5dec4,0,1,0,0,0,0,2026-08-05 21:41:21.980,2026-08-05 21:41:21.980
5825,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959
5826,ffcf3b9c-8cc8-4fca-a93a-e01a6fd830f0,1,1,1,0,0,0,2026-05-06 14:42:42.170,2026-05-06 14:44:23.800
5827,fff7862d-4b2c-4140-a4c5-509b48ed31b4,0,1,0,0,0,1000,2025-11-12 01:01:58.698,2025-11-12 01:02:16.561
5828,fff940d1-0786-4ee5-a75a-3bbda4e50f7a,0,1,0,0,0,0,2026-04-29 13:33:15.703,2026-04-29 13:33:15.703